In [4]:
"""Task 1
Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
3
45
83
21
"""
#create the file name
Number = open("number.txt", "w")

Number

<_io.TextIOWrapper name='number.txt' mode='w' encoding='cp1252'>

In [5]:
Number =open("number.txt", "r")

Number

<_io.TextIOWrapper name='number.txt' mode='r' encoding='cp1252'>

In [6]:
print(Number.read())

In [8]:
Number = open("number.txt", "w")

for i in (3,45,83,21):

    Number.write(str(i))

    Number.write("\n")

Number.close()

Number


<_io.TextIOWrapper name='number.txt' mode='w' encoding='cp1252'>

In [60]:
"""Task 2a
Write a program to ask a student for their percentage mark and convert this to a grade.
"""

Chemistry_mark = int(input("What is your percentage mark?:"))

Biology_mark = int(input("What is your percentage mark?:"))

Math_mark = int(input("What is your percentage mark?:"))

English_mark = int(input("What is your percentage mark?:"))

Physisc_mark = int(input("What is your percentage mark?:"))

Chm =Chemistry_mark
Bio = Biology_mark
Mat = Math_mark
En = English_mark
Phy = Physisc_mark

def mark_grade (Chm,Bio,Mat,En,Phy):
    Total = Chm + Phy + Bio + Mat + En
    
    Percentage = (Total / 500) * 100

    return Percentage

if mark_grade(Chm,Bio,Mat,En,Phy) <=50:
    
    print("C")

elif mark_grade(Chm,Bio,Mat,En,Phy) >=90:
    print ( "A"  )




C


In [61]:
"""Task 2b
Ask the user for their target grade and print this with their mark.
"""
grade_target = str(input("what is your target grade?"))

print(grade_target,":", mark_grade(Chm,Bio,Mat,En,Phy))


A : 42.0


In [62]:
"""
If their target grade > exam grade display a suitable message.
If their target grade = exam grade display a suitable message•
If their target grade < exam grade display a suitable message.
"""
exam_grade = "C"

if grade_target > exam_grade:
    print("You didnt make it to the required grade")
else:
    if grade_target == exam_grade:
        print("Weldone")
    elif grade_target < exam_grade:
        print("You failed")



You failed


In [3]:
"""task 3
Create a 1D array of numbers from 0 to9
1.Create a 1D array of numbers from 0 to9
2.Create a 3×3 NumPy array of allBoolean value Trues
3.Extract all odd numbers from array of 1-10
4.Replace all odd numbers in an array of 1-10 with the value -1
5.Convert a 1D array to a 2D array with 2rows
6.Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculatetotalsExtension
"""
import numpy as np

In [17]:
#1

import numpy as np

array = np.arange(0,9)

print(array)


[0 1 2 3 4 5 6 7 8]


In [23]:
#2
values = np.arange(1,10) # create an array of values from 1 to 10

bool_arr =np.array(values, dtype =bool) #dype parameter to specify the values to only be boolean

boolen_arr = bool_arr.reshape(3,3) #reshapes the array

print(boolen_arr)

print

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


<function print>

In [30]:
#3

a = np.arange(1,10) #array of numbers from 1-10

print(a[a % 2 ==1])


[1 3 5 7 9]


In [40]:
#4
b = np.arange(1,10)

c =np.where(a[a%2])

d = np.clip(c, -1,1)

print(c)


(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)


In [46]:
#5

one_array =np.arange(3,7)

two_D = one_array.reshape(2,2)

print(two_D)

[[3 4]
 [5 6]]


In [60]:
#6

z = np.arange(1,10).reshape(3,3)

x = np.arange(10,19).reshape(3,3)

q = np.vstack(z)#vertically stack array

v = np.vstack(x) #vertically stack array

d = np.dot(q,v) #prduce product of the elements in the array

e = np.sum(d)# produce sum of the elements in the array

print(d)
print(e)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [80]:
#extension 2

a = [1,2,3,4,5]

b = [4,5,6,7,8,9]


print(np.unique(b))#removes repeating elements in the array




[4 5 6 7 8 9]
